// <auto-generated />
namespace Workpaces.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AppSet2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppSet2));
        
        string IMigrationMetadata.Id
        {
            get { return "202411192010402_AppSet2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
