// <auto-generated />
namespace Workpaces.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class estadisticas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(estadisticas));
        
        string IMigrationMetadata.Id
        {
            get { return "202412180122563_estadisticas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
